### ISSUE TITLE
框选图形拖动的时候，连接线好像不会跟着移动

### ISSUE THREAD

**Issue by nobugnorunning** [qlynick/leafer-x-connector#4]
![image](https://github.com/user-attachments/assets/b5d66a98-321f-41de-92be-3fa9514a2625)
在项目中使用了group添加了线和两个图形，但是在移动的时候还是遇到了这样的问题，不知道是不是我的操作有误还是什么，希望得到解答

**Comment by nobugnorunning** [comment]
🙏

**Comment by qlynick** [comment]
不是线，要添加LeaferXQnConnector

**Comment by 123164867376464646** [comment]
![Image](https://github.com/user-attachments/assets/5a1714ca-e5fe-4162-afc0-e180a9171a97)

![Image](https://github.com/user-attachments/assets/14325838-c842-4d9e-aaa6-69584d3a6b7c)
图一是框选两个元素，同时移动，原本的连线没有同步更新连接，只有移动某一元素时才会更新
